WPI-PartyList/PartyList/urls.py
from django.conf.urls import patterns, url
from django.views.generic import RedirectView

urlpatterns = patterns('',
	url(r'^$', RedirectView.as_view(pattern_name='PartyList.views.index'), name='parties'),
	url(r'^all/$', 'PartyList.views.index'),
	url(r'^add/$', 'PartyList.views.add_party'),
	url(r'^manage/$', 'PartyList.views.manage_parties', name='manage_parties'),
	url(r'^edit/(?P<party>[\d]+)/$', 'PartyList.views.edit_party'),
	url(r'^delete/(?P<party>[\d]+)/$', 'PartyList.views.delete_party'),
	url(r'^view/(?P<party>[\d]+)/guests/$', 'PartyList.views.guests'),
	url(r'^view/(?P<party>[\d]+)/guests/create/$', 'PartyList.api.create'),
	url(r'^view/(?P<party>[\d]+)/guests/destroy/(?P<guestID>[\d]+)/$', 'PartyList.api.destroy'),
	url(r'^view/(?P<party>[\d]+)/guests/signIn/(?P<guestID>[\d]+)/$', 'PartyList.api.signin'),
	url(r'^view/(?P<party>[\d]+)/guests/signOut/(?P<guestID>[\d]+)/$', 'PartyList.api.signout'),
	url(r'^view/(?P<party>[\d]+)/guests/poll/$', 'PartyList.api.poll'),
	url(r'^view/(?P<party>[\d]+)/guests/export/$', 'PartyList.api.export_list'),
	url(r'^view/(?P<party>[\d]+)/guests/count/$', 'PartyList.api.updateCount'),
	url(r'^view/(?P<party>[\d]+)/guests/count/poll/$', 'PartyList.api.pollCount'),
	url(r'^view/(?P<party>[\d]+)/guests/init/$', 'PartyList.api.initPulse'),
)

WPI-PartyList/Secure/urls.py
from django.conf.urls import patterns, include, url

from Secure import views

urlpatterns = patterns('',
	url(r'^$', 'Secure.views.index'),
    url(r'^parties/', include('PartyList.urls')),
    url(r'^users/', include('UserInfo.secure_urls')),
)

WPI-PartyList/WPI-PartyList/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static 

# Uncomment the next two lines to enable the admin:
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:

    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^users/', include('UserInfo.urls')),
    url(r'^secure/', include('Secure.urls')),
    url(r'^', include('PubSite.urls')),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

WPI-PartyList/PartyList/models.py
from django.db import models
from django.contrib.auth.models import User
from django import forms
from datetime import datetime

from UserInfo.models import Fraternity

class Party(models.Model):
	"""
		Model to represent a party.
	"""

	# NOTE: In the future, this path should be changed to be in protected file space so it is not
	# accessible to the public.

	name = models.CharField(max_length=100)
	date = models.DateField()
	guycount = models.IntegerField(default=0)
	girlcount = models.IntegerField(default=0)
	fraternity = models.ForeignKey(Fraternity)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	def isPartyMode(self):
		# Find out if we are in party mode
		closedatetime = datetime(self.date.year, self.date.month, self.date.day, 20)
		return closedatetime < datetime.now()

	#Setup meta info about this model
	class Meta:
		verbose_name_plural = "Parties"
		verbose_name = "Party"
		permissions = (
            ("manage_parties", "Can manage Parties"),
        )

class Guest(models.Model):
	"""
		Model to represent a party guest
	"""
	name = models.CharField(max_length=100, db_index=True)
	birthDate = models.DateField(blank=True,auto_now=True)
	gender = models.CharField(max_length=100)
	cardID = models.CharField(max_length=100, blank=True)
	createdAt = models.DateTimeField(auto_now_add=True)
	updatedAt = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return self.name

	def __str__(self):
		return self.name

	def __iter__(self):
		"""return a ** iterator of field,value"""
		for i in self._meta.get_all_field_names():
			yield (i, getattr(self,i))

	def __cmp__(self,other):
		pass
		#apparently django does not use this during the order_by query

	#Setup meta info about this model
	class Meta:
		verbose_name_plural = "Guests"
		verbose_name = "Guest"

class PartyGuest(models.Model):
	"""
		Model to represent a guest for a specific party.
	"""
	party = models.ForeignKey(Party, related_name="party_for_guest", default=1)
	guest = models.ForeignKey(Guest, related_name="guest", default=1, db_index=True)
	addedBy = models.ForeignKey(User, related_name="added_by", default=1)
	createdAt = models.DateTimeField(auto_now_add=True, db_index=True)
	signedIn = models.BooleanField(default=False)
	everSignedIn = models.BooleanField(default=False)
	timeFirstSignedIn = models.DateTimeField(auto_now_add=True)

	def __unicode__(self):
		return self.guest.name

	def __str__(self):
		return self.guest.name

	def __iter__(self):
		"""return a ** iterator of field,value"""
		for i in self._meta.get_all_field_names():
			yield (i, getattr(self,i))

	#Setup meta info about this model
	class Meta:
		verbose_name_plural = "Party Guests"
		verbose_name = "Party Guest"

	def toJSON(self):
		data = {}
		data['id'] = self.id
		data['name'] = self.guest.name
		data['addedByName'] = self.addedBy.first_name + " " + self.addedBy.last_name
		data['addedByID'] = self.addedBy.id
		data['signedIn'] = self.signedIn

		return data

WPI-PartyList/PartyList/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import  login_required
from PartyList.models import Party
from django.http import HttpResponse
from PartyList.widgets import PartyForm, EditPartyInfoForm
import json

@login_required
def index(request):
    """
        View for all parties
    """

    parties = Party.objects.all().order_by("date")
    context = {
        'parties': parties,
    }
    return render(request, 'parties.html', context)

@login_required
def guests(request, party):
    """
        View for all guests on the list for a party
    """

    try:
        requested_party = Party.objects.get(pk=party)
    except:
        return redirect("PartyList.views.index")

    partymode = requested_party.isPartyMode()

    context = {
            'party': requested_party,
            'partymode': partymode,
    }

    return render(request, 'partyguests.html', context)


def add_party(request):
    context = {
        'message': []
    }

    if request.method == 'POST':
        form = PartyForm(request.POST)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.fraternity = request.user.fraternity
            obj.save()
            context['message'].append(obj.name + " successfully added.")
            return redirect('manage_parties')
        else:
            context['message'].append("Error adding party.")

    return render(request, 'add_party.html', context)

def manage_parties(request):
    if request.user.fraternity.manager == request.user:
        all_parties = Party.objects.filter(fraternity=request.user.fraternity).order_by("date").reverse()

    context = {
        'all_parties': all_parties,
    }

    return render(request, 'manage_parties.html', context)

def edit_party(request, party):
    """
        Provides a view to edit a single party.
    """
    # Retrieve the party that we are trying to edit
    try:
        requested_party = Party.objects.get(pk=party)
    except:
        return redirect("PartyList.views.manage_parties")

    errors = None

    if request.method == 'POST':
        # If this is a POST request, the form has been submitted
        form = EditPartyInfoForm(request.POST, request.FILES, instance=requested_party)

        if form.is_valid(): # Check that form is valid
            form.save()
            return redirect("PartyList.views.manage_parties")
    else:
        form = EditPartyInfoForm(instance=requested_party)

    context = {
        'requested_party': requested_party,
        'form': form,
        'error': form.errors
    }

    return render(request, 'edit_party.html', context)

def delete_party(request, party):
    """
        Deletes the party with the ID that is sent in the post request
    """

    if request.method == 'POST':
        try:
            party = Party.objects.get(pk=party)
        except:
            return redirect("PartyList.views.manage_parties")

        party.delete()

    return redirect("PartyList.views.manage_parties")

WPI-PartyList/PartyList/templates/add_party.html
{% extends "secure_base.html" %}
{% block title %}New Party{% endblock %}

{% block module_includes %}
	{% load staticfiles %}
	<script type="text/javascript" src='{% static "js/lib/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "js/lib/bootstrap-datetimepicker.min.js" %}'></script>
	<link rel="stylesheet" type="text/css" href='{% static "css/lib/bootstrap-datetimepicker.min.css" %}'/>
{% endblock %}

{% block content %}
<h3>Add a new party.</h3>

<form enctype="multipart/form-data" method="post" action="{% url 'PartyList.views.add_party' %}" role="form" class="centered medium">	
	{% csrf_token %}
	{% if message %}
	<div class="alert alert-info">
		{% for msg in message %}
		<p>{{ msg }}</p>
		{% endfor %}
	</div>
	{% endif %}
	<div class="form-group">
  		<label class="control-label" for="id_name">Party Name</label>
  		<input type="text" id="id_name" name="name" maxlength="50" class="form-control"/>
	</div>
	<div class="form-group">
  		<label class="control-label" for="datepicker">Party Date</label>
  		<input type="text" id="datepicker" name="date" maxlength="50" class="form-control"/>
	</div>
	<button type="submit" class="btn btn-primary pull-right">Add Party</button>
</form>
{% endblock %}

{% block embedded_js %}

<script type="text/javascript">
	// Initialize all date pickers on the page.
	$('#datepicker').datetimepicker({
		pickTime: false,
		showToday: true,
		minDate: moment()
	});
</script>

{% endblock %}

WPI-PartyList/PartyList/templates/edit_party.html
{% extends "secure_base.html" %}

{% block title %}Edit Party{% endblock %}

{% block module_includes %}
	{% load staticfiles %}
	<script type="text/javascript" src='{% static "js/lib/moment.min.js" %}'></script>
	<script type="text/javascript" src='{% static "js/lib/bootstrap-datetimepicker.min.js" %}'></script>
	<link rel="stylesheet" type="text/css" href='{% static "css/lib/bootstrap-datetimepicker.min.css" %}'/>
{% endblock %}

{% block content %}
	<h3>Edit the fields below to change the party's info.</h3>
	<form enctype="multipart/form-data" method="post" action="{% url 'PartyList.views.edit_party' requested_party.pk %}" class="medium centered" role="form">
		{% csrf_token %}
		{% if error %}
		<div class="alert alert-warning">
			<strong>Error</strong>
			<p>{{ error }}</p>
		</div>
		{% endif %}
		<div class="form-group">
	  		<label for="id_name" class="control-label">Party Name</label>
	  		{{form.name}}
		</div>
		<div class="form-group">
			<label for="id_date" class="control-label">Party Date</label>
			{{form.date}}
		</div>
		<button type="submit" class="btn btn-primary pull-right">Save</button>
	</form>

	<script>
		$("#id_date").attr("data-date-format", "YYYY-MM-DD"); 
		$("#id_date").datetimepicker({
			pickTime: false,
			showToday: true,
			minDate: moment()
		});
	</script>
{% endblock %}

WPI-PartyList/PartyList/templates/manage_parties.html
{% extends "secure_base.html" %}
{% block title %}Sigma Pi Secure - Manage Parties {% endblock %}

{% block content %}
<h3>Edit and delete existing parties.</h3>


{% endblock %}

WPI-PartyList/PartyList/templates/parties.html
{% extends "secure_base.html" %}

{% block title %}{% endblock %}

{% block content %}
<div class="row">
	<div class="col-md-10 col-md-offset-1">
		<h3>{{user.fraternity}} Party List Tracker</h3>
		{% if is_manager %}
      Welcome, {{ user.fraternity }} manager.
		{% else %}
      Welcome, {{ user }}.
		{% endif %}
	</div>

	<div class="col-md-10 col-md-offset-1">
		{% for party in parties %}
		<a href="{% url 'PartyList.views.guests' party.pk %}">
			Guest List for {{p}}
		</a>
		{% endfor %}
  </div>
</div>

{% endblock %}

WPI-PartyList/PartyList/templates/partyguests.html
{% extends "secure_base.html" %}

{% block title %}Sigma Pi Secure - {{ party.name }}{% endblock %}

{% block module_includes %}
	{% load staticfiles %}	
	<script type="text/javascript" src="{% static 'js/secure/party.guest.js' %}"></script>

	<link rel='stylesheet' type='text/css' href='{% static "css/secure/party.guests.css" %}' />
{% endblock %}

{% block content %}

<h3>{{ party.name }} - {{ party.date }} Guest List</h3>

<!-- Action navigation -->
<div class="actions">
	<ul class="nav nav-pills">
		<li>
			<a href="{% url 'PartyList.api.export_list' party.pk %}">
				<span class="glyphicon glyphicon-download"></span> Export List
			</a>
		</li>
	</ul>
</div>

<!-- Navigation and Counter -->
<div class="navbar-fixed-bottom">
	<ul class="section">
		<li id="message-ux" style="display:none;"></li>
	{% if not partymode %}
		<li class="title">View:</li>
		<li class="active">
			<a href="#" id="all-guests">All Guests 
				<span class="badge">T: <span id="all-guests-count">0</span></span>
				<span class="badge">M: <span id="all-male-count">0</span></span>
				<span class="badge">F: <span id="all-female-count">0</span></span>
			</a>
		</li>
		<li>
			<a href="#" id="my-guests">My Guests 
				<span class="badge">T: <span id="my-guests-count">0</span></span>
				<span class="badge">M: <span id="my-male-count">0</span></span>
				<span class="badge">F: <span id="my-female-count">0</span></span>
			</a>
		</li>
	{% else %}
		<li class="title">Counts:</li>
		<li>
			
			Guys: <span class="count" id="M">0</span>
			<button type="button" class="btn btn-default btn-sm sub-count" id="M">
				<span class="glyphicon glyphicon-minus"></span> 
			</button>
			<button type="button" class="btn btn-default btn-sm add-count" id="M">
			 	<span class="glyphicon glyphicon-plus"></span>
			 </button>
		</li>
		<li>
			Girls: <span class="count" id="F">0</span>
			<button type="button" class="btn btn-default btn-sm sub-count" id="F">
				<span class="glyphicon glyphicon-minus"></span> 
			</button>
			<button type="button" class="btn btn-default btn-sm add-count" id="F">
			 	<span class="glyphicon glyphicon-plus"></span>
			 </button>
		</li>
		<li>
			Total: <span class="count" id="total">0</span>
		</li>
	{% endif %}
	</ul>
</div>

<!-- Search all guests -->
<div role="form" class="search-box">
	<label class="sr-only" for="searchbox">Guest or Brother Name</label>
	<input type="text" class="form-control" id="search-box" placeholder="Search by Guest or Brother Name"/>
	<button type="submit" class="btn btn-primary" id="search-btn">Search</button>
</div>

<!-- Guest List -->
<div class="container-fluid">
	<div class="row">
		<div class="col-xs-12 col-sm-6">
			<h4>Male Guests</h4>
			<div class="add-guest-form">
				<input type="text" class="form-control" style="width: auto;" id="add-male-name" placeholder="{% if partymode %}Write-in{% else %}Add{% endif %} Male Guest"/>
				<button type="submit" class="btn btn-default" id="add-male-btn">
					<span class="glyphicon glyphicon-plus"></span>
				</button>
			</div>

			<div class="loader" id="M">
				<p>Loading Guest List...</p>
			</div>
			<div class="guest-list male" id="M">
			</div>
		</div>

		<div class="col-xs-12 col-sm-6">
			<h4>Female Guests</h4>
			<div class="add-guest-form">
				<input type="text" class="form-control" style="width: auto;" id="add-female-name" placeholder="{% if partymode %}Write-in{% else %}Add{% endif %} Female Guest"/>
				<button type="submit" class="btn btn-default" id="add-female-btn">
					<span class="glyphicon glyphicon-plus"></span>
				</button>
			</div>
			<div class="loader" id="F">
				<p>Loading Guest List...</p>
			</div>
			<div class="guest-list female" id="F">
			</div>
		</div>
	</div>
</div>

<!-- Hacky way to add guests from the client side on the fly without hardcoding the html and css in javascript. Replace this with the use of a front end MVC library such as Ember or Backbone. -->
<div id="guest-template" class="guest hidden">
	{% if partymode %}
	<span class="glyphicon glyphicon-ok status checked-in"></span>
	{% else %}
	<span class="glyphicon glyphicon-remove status present remove-guest"></span>
	{% endif %}
	<div class="name"></div>
	<div class="details"></div>
</div>
{% endblock %}